#×¢²áÖĞĞÄÅäÖÃ
spring:
  application:
    name: register-center
server:
  port: 5050
eureka:
  client:
    serviceUrl:
      defaultZone: localhost:${server.port}/eureka/
    register-with-eureka: true
